### ISSUE TITLE
PDA doesn't run

### ISSUE THREAD

**Issue by bca-benise** [davidbuzatto/YAAS#2]
I created a simple two-state PDA with q0 marked Initial and q1 marked Final.  For the first state I created a self-looping transition on symbol a, with stack top epsilon (I used the checkmark), and stack operation was to push an "a"

(Interestingly, this was notated as "a,ε/aε" -- I'm not sure what the second ε in that designates?  Perhaps this is the origin of the bug?)

This should push a's on the input string to the stack.

I then made an epsilon transition ("ε, ε/ε") to state q1.

finally, I made a self-looping transition "b, a/ε" on q1.  

The machine should accept any string a^mb^n where n>=m, but when I try the string aabb, it says that it rejects, and the play mode won't allow me to view what is happening.

**Comment by davidbuzatto** [comment]
It's because you misseunderstood the notation The notation tha I'm using is from Hopcroft, Motwani and Ullman (Introduction to Automata Theory, Languages, and Computation, 2006). Your example should be modeled like the image below:

![example](https://github.com/davidbuzatto/YAAS/assets/313050/2f14eef2-c2c6-459c-8d83-07de4fcd622a)

The used notation will be adressed in issue #4.
